## ПРАКТИЧНА РОБОТА 1

### Варіант 15

In [1]:
import numpy as np

Завдання 1: Створіть одновимірний масив (вектор) з найбільшими простими числами, не перевищуючи 30, та виведіть його значення. 

In [2]:
a = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])

print("а = ", a)

а =  [ 2  3  5  7 11 13 17 19 23 29]


Завдання 2: Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями квадратів найближчого більшого парного числа для кожного натурального числа, починаючи з 1, та виведіть його значення. 

In [3]:
a = np.arange(2, 20, 2)
sq_matrix = np.reshape(a ** 2, (3, 3))

print(sq_matrix)

[[  4  16  36]
 [ 64 100 144]
 [196 256 324]]


Завдання 3: Створіть масив розміром 6x6, заповніть його випадковими цілими числами від -50 до 50 та знайдіть добуток непарних чисел. 

In [4]:
a = np.random.randint(-50, 51, (6, 6))

prod_odd = np.prod(a[a % 2 != 0])

print("a = ", a)
print("Добуток непарних чисел", prod_odd)

a =  [[ 21  16   4  24  36  36]
 [ 49 -12  -1 -30 -14  -9]
 [-24  37  41 -46  11  14]
 [-37 -20   6 -32 -35 -34]
 [ 18  39 -14  29  -1  37]
 [ 14   9  29 -13  -5 -37]]
Добуток непарних чисел 1213920979


Завдання 4: Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-рядок, що містить максимальні елементи в кожному стовпці. 

In [5]:
a = np.random.rand(4, 4)

cols_max = a.max(axis = 0)

print("а = ", a)
print("Максимальні елементив кожному стовпці = ", cols_max)

а =  [[0.70196198 0.21626179 0.83921221 0.81751465]
 [0.88502968 0.0492519  0.72934894 0.90782318]
 [0.09662962 0.98785122 0.61531948 0.46960878]
 [0.27947317 0.02485088 0.31887387 0.733194  ]]
Максимальні елементив кожному стовпці =  [0.88502968 0.98785122 0.83921221 0.90782318]


Завдання 5: Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими числами в діапазоні від -10 до 10 та виконайте на них поелементні операції додавання, віднімання та множення. 

In [6]:
a = np.random.randint(-10, 11, 7)
b = np.random.randint(-10, 11, 7)

print("a = ", a)
print("b = ", b)
print("Додавання елементів матриць = ", a + b)
print("Віднімання елементів матриць = ",a - b)
print("Множення елементів матриць = ",a * b)

a =  [ -5   2   5   6  -9   1 -10]
b =  [ 0  1 -9  8 10  6  8]
Додавання елементів матриць =  [-5  3 -4 14  1  7 -2]
Віднімання елементів матриць =  [ -5   1  14  -2 -19  -5 -18]
Множення елементів матриць =  [  0   2 -45  48 -90   6 -80]


Завдання 6: Створіть два вектори розміром 7, заповніть їх довільними цілими числами та знайдіть їх скалярний добуток. 

In [7]:
a = np.random.randint(1, 11, size=7)
b = np.random.randint(1, 11, size=7)

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("Скалярний добуток векторів дорівнює:", dot_a_b)

a =  [10  9  5  5 10  7  4]
b =  [ 1 10  4 10  9  9  8]
Скалярний добуток векторів дорівнює: 355


Завдання 7: Створіть дві матриці розміром 4x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою. 

In [8]:
a = np.random.randint(1, 11, (4, 2))
b = np.random.randint(1, 11, (2, 2))

dot_a_b = np.dot(a, b);

print("a = ", a)
print("b = ", b)
print("Результат перемноження матриць: ", dot_a_b)

a =  [[ 9  1]
 [10  8]
 [ 2  9]
 [ 2  8]]
b =  [[ 2  4]
 [10  5]]
Результат перемноження матриць:  [[ 28  41]
 [100  80]
 [ 94  53]
 [ 84  48]]


Завдання 8: Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю. 

In [9]:
a = np.random.randint(1, 8, size=(2, 2))

print("Вихідна матриця:")
print(a)

# перевірка, чи можна знайти обернену матрицю
if np.linalg.det(a) == 0:
    print("Матриця не має оберненої матриці.")
else:
    # знаходження оберненої матриці
    inv_a = np.linalg.inv(a)
    print("Обернена матриця:")
    print(inv_a)

Вихідна матриця:
[[3 7]
 [7 7]]
Обернена матриця:
[[-0.25        0.25      ]
 [ 0.25       -0.10714286]]


Завдання 9: Створіть матрицю розміром 3x5, заповніть її випадковими цілими числами в діапазоні від 0 до 1 та транспонуйте її. 

In [10]:
a = np.random.randint(0, 2, (3, 5))

print("а = ", a)

a_transp = np.transpose(a)

print("Транспонована матриця:")
print(a_transp)

а =  [[1 0 0 1 1]
 [0 1 0 1 1]
 [0 0 0 0 1]]
Транспонована матриця:
[[1 0 0]
 [0 1 0]
 [0 0 0]
 [1 1 0]
 [1 1 1]]


Завдання 10: Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток вектора на матрицю. 

In [11]:
a = np.random.rand(3, 4)
b = np.random.randint(1, 11, 4)

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("Добуток вектора на матрицю", dot_a_b)

a =  [[0.84437112 0.46119304 0.25113384 0.27456084]
 [0.34764608 0.13644974 0.10870555 0.29002027]
 [0.0553104  0.51307226 0.52930216 0.27591403]]
b =  [1 7 4 8]
Добуток вектора на матрицю [7.27374447 4.05777861 7.9713371 ]


Завдання 11: Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть суму елементів матриці, які менше за відповідний елемент вектору. 

In [12]:
a = np.random.rand(2, 3)
b = np.random.rand(3)

res = np.sum(a[a < b])

print("a = ", a)
print("b = ", b)
print("res = ", res)

a =  [[0.89348662 0.23651532 0.74654552]
 [0.89631224 0.86336114 0.95883885]]
b =  [0.39833433 0.12203578 0.69098859]
res =  0.0


Завдання 12: Створіть дві матриці розміром 8x8, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть різницю елементів першого стовпця першої матриці. 

In [13]:
a = np.random.randint(1, 11, (8, 8))
b = np.random.randint(1, 11, (8, 8))

res = a[0:, 0] - b[0:, 0]

print("a = ", a)
print("b = ", b)
print("res = ", res)

a =  [[ 5  7  7  3  7  4  5  9]
 [ 8  1  9  7  6  5  9  7]
 [ 7  9  4  7  2  4 10  4]
 [10 10  8  8  5  7  3  3]
 [ 8  6  4  4  8  7  3  4]
 [ 9  1  7  5  4  5  4  4]
 [ 5  5  4  6 10  6  1  8]
 [ 6  9  2  1  3  4 10  1]]
b =  [[ 6  4  2  7  1  3  9  3]
 [ 1  6  2  3  4  5  7  1]
 [ 6  6  5  6  7  5  2  1]
 [ 5 10  6  9  6  3  5  9]
 [ 3  2 10  8  7  5  3  3]
 [ 8  9  6  6  5  4  6  6]
 [ 9  1  6 10  1  4  8  2]
 [ 2  9  4  5  4  6  8  2]]
res =  [-1  7  1  5  5  1 -4  4]


Завдання 13: Створіть дві матриці розміром 7x7, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть добуток їх елементів. 

In [14]:
a = np.random.rand(7, 7) * 2 - 1
b = np.random.rand(7, 7) * 2 - 1

prod_a = np.prod(a) 
prod_b = np.prod(b)
res = prod_a * prod_b

print("a = ", a)
print("b = ", b)
print("Добуток елементів матриць:", res)

a =  [[-0.7940097  -0.75250698 -0.60064198  0.61143228 -0.54561273 -0.7167233
   0.09164598]
 [-0.48758919  0.38723332 -0.66783997 -0.65679278 -0.90009674 -0.53783829
  -0.64040875]
 [ 0.68968172 -0.33458874 -0.45980698 -0.98741367 -0.67664285 -0.85297918
   0.0376397 ]
 [-0.03435778 -0.76935592  0.28004487  0.19663904 -0.46737673 -0.38840441
  -0.54003361]
 [-0.84785622  0.34695655  0.493505    0.19785563 -0.56161516 -0.03977345
   0.20176257]
 [ 0.8785119  -0.3271137  -0.14709191 -0.40533499 -0.23075562 -0.40017761
   0.90080725]
 [-0.50716046  0.49607963  0.88443105 -0.97164604 -0.78694846  0.9502163
   0.95606134]]
b =  [[ 0.29414936  0.56824919 -0.73894624 -0.35649265 -0.12643306  0.04231591
  -0.77324658]
 [-0.39504351  0.54219808 -0.28870381 -0.0027709   0.97699427  0.69859343
  -0.70270546]
 [-0.92013948 -0.77350818 -0.10811573 -0.01869105  0.7916333  -0.36898493
  -0.44409989]
 [ 0.73459155  0.04792934 -0.78737608 -0.63529533 -0.35721452  0.5273828
  -0.74413099]
 [ 0.43416349

Завдання 14: Створіть матрицю розміром 7x7, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть добуток елементів матриці, які більше за їх середнє арифметичне значення. 

In [15]:
a = np.random.rand(7, 7) * 20 - 10

mean_a = np.mean(a)
res = np.prod(a[a > mean_a])

print("a = ", a)
print("Mean value = ", mean_a)
print("Result = ", res)

a =  [[-0.87744769  4.55283732 -7.90038179  5.49450391 -5.56643986 -7.75497707
   5.21860747]
 [ 6.9193671  -9.67732856 -5.70897769 -1.13708114  4.52273174  2.33611589
   9.53605934]
 [ 2.51915294 -4.90589258  3.00885773 -9.89258493  3.52538651 -9.99417737
   3.0826977 ]
 [ 5.24665847  1.33055703  4.28859955 -8.22160085  6.3751      3.689526
   7.31774905]
 [-7.85390066 -4.83567249 -2.06430252  7.43564332 -2.7339037   1.72785429
  -3.39490711]
 [ 3.2333622   9.44471706  2.48475888 -1.71241465 -7.46993827  3.67916327
  -8.4241057 ]
 [ 8.1319546   6.4029695  -3.84702547  8.56571064  7.32062602  7.6026197
   5.84516993]]
Mean value =  0.7523672875400711
Result =  2.010514519013742e+19


Завдання 15: Створіть матрицю розміром 9x9, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить найбільше за модулем ціле значення в кожному рядку матриці. 

In [16]:
a = np.random.rand(9, 9) * 1 - 0.5

rows_max_abs = np.max(np.abs(a), axis = 1)
col_vec = rows_max_abs.reshape((-1, 1))

print("a = ", a)
print("Result: ", col_vec)

a =  [[-0.24663532  0.11628765 -0.04997216  0.25776982  0.12850368  0.41256942
   0.46592949  0.30437234  0.07104212]
 [ 0.28722069  0.12554946 -0.05591424  0.12338502  0.4096416  -0.36637847
   0.47403847  0.02998711  0.15075595]
 [-0.27061694  0.47590018  0.08224186  0.42433274  0.41035275 -0.11363
  -0.15026026 -0.03534714 -0.49367432]
 [-0.26178765 -0.0724722   0.37597828 -0.11199407 -0.46811791  0.13447251
  -0.03109525  0.17382592  0.25342322]
 [-0.00574945 -0.07782062 -0.22558603  0.00692535  0.4965977   0.29930473
  -0.22557916  0.21903774 -0.46581915]
 [-0.36265547  0.14304035 -0.40939681  0.27327352 -0.40865298 -0.26863624
  -0.37417079 -0.40299716 -0.35351104]
 [-0.21412572 -0.23395489 -0.32979692  0.0748274  -0.30228612  0.23148595
   0.3730816   0.48108766  0.09704508]
 [ 0.27543987 -0.02945908 -0.18587508 -0.17426019 -0.09573403 -0.04097869
  -0.4446556  -0.45725388 -0.04441297]
 [-0.45264266 -0.00415045  0.26330775  0.43682443 -0.14353079  0.44329205
   0.08475292  0.024

На практичній роботі я вдосконалила знання із мови програмування - Python, а саме створення одновимірних та двовимірних масивів, матриць та арифметичні операції над ними (додавання, віднімання, множення, скалярний добуток та інші). Також навчилася правильно агрегувати дані масиву і пригадала, як здійснюється транспортування та зміна форми матриці.